name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup JDK 17 (AGP 8 butuh minimal Java 17)
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Setup Gradle cache & CLI
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 4. Generate gradlew (jika belum ada di repo)
      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.2.1
          chmod +x gradlew

      # 5. Decode keystore dari secret
      - name: Prepare Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/yoga.jks

      # 6. Build APK Release
      - name: Build Release APK
        run: |
          ./gradlew :app:assembleRelease --warning-mode all \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/yoga.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      # 7. Upload hasil APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      # 8. Build AAB Release
      - name: Build Release AAB
        run: |
          ./gradlew :app:bundleRelease --warning-mode all \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/yoga.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      # 9. Upload hasil AAB
      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/*.aab
